version: '3.7'

services: 
    app:
        container_name: ${PROJECT_NAME}-app
        image: magento-nginx:1.17
        build: ./images/nginx/1.17
        ports: 
            - "80:8080"
            - "443:8443"
        environment: 
            - HOSTNAME=${PROJECT_HOST}
        links:
            - db
            - phpfpm
        volumes: &appvolumes
            - ~/.composer:/var/www/.composer:delegated
            - appdata:/var/www/html
            - sockdata:/sock
            - ssldata:/etc/nginx/certs

    phpfpm:
        container_name: ${PROJECT_NAME}-phpfpm
        image: magento-php:7.3-fpm-2
        build: ./images/php/7.3
        environment:
            - PHP_IDE_CONFIG=serverName=docker
        links:
            - db
        volumes: *appvolumes

    db:
        container_name: ${PROJECT_NAME}-db
        image: percona:5.7
        ports:
            - "3306:3306"
        env_file: cfg/db.env
        volumes: 
            - dbdata:/var/lib/mysql

    redis:
        container_name: ${PROJECT_NAME}-redis
        image: redis:5.0

    rabbitmq:
        container_name: ${PROJECT_NAME}-rabbitmq
        image: rabbitmq:3.7-management
        ports:
            - "15672:15672"
            - "5672:5672"
        volumes:
            - rabbitmqdata:/var/lib/rabbitmq

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PROJECT_NAME}-phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - "8080:80"
        volumes:
            - /sessions

#    elasticsearch:
#        container_name: ${PROJECT_NAME}-elasticsearch
#        image: magento-elasticsearch:6.5.4-0
#        build: ./images/elasticsearch/6.5
#        ports:
#            - "9200:9200"
#            - "9300:9300"

volumes:
    appdata:
    dbdata:
    sockdata:
    rabbitmqdata:
    ssldata: