version: "3.7"

services:
  app:
    volumes: &appvolumes
        - ./../html/app/code:/var/www/html/app/code:delegated
        - ./../html/app/design:/var/www/html/app/design:delegated
        - ./../html/var/log:/var/www/html/var/log:delegated
        # - ./../html/app/etc:/var/www/html/app/etc:delegated
        # - ./../html/composer.json:/var/www/html/composer.json:delegated
        # - ./../html/composer.lock:/var/www/html/composer.lock:delegated
        # - ./../html/auth.json:/var/www/html/auth.json:delegated
        # - ./../html/nginx.conf.sample:/var/www/html/nginx.conf.sample:delegated
        # - ./../html/pub/media:/var/www/html/pub/media:delegated
        # For Linux commit previous and ucommit next
        # - ./../html:/var/www/html:delegated

  phpfpm:
    volumes: *appvolumes

  mailhog:
    container_name: ${PROJECT_NAME}-mailhog
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"
    networks:
      - docker-network

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  volumes: *appvolumes