version: "3.7"

services:
  app:
    volumes: &appvolumes
        - ./../html/app/code:/var/www/html/app/code:delegated
        - ./../html/app/design:/var/www/html/app/design:delegated
        - ./../html/app/etc:/var/www/html/app/etc:delegated
        - ./../html/var/log:/var/www/html/var/log:delegated
        - ./../html/composer.json:/var/www/html/composer.json:delegated
        - ./../html/composer.lock:/var/www/html/composer.lock:delegated
        - ./../html/nginx.conf:/var/www/html/nginx.conf:delegated

  phpfpm:
    volumes: *appvolumes

  mailhog:
    container_name: m2-mailhog
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  volumes: *appvolumes