version: '3.7'

services: 
    magento:
        image: magento-nginx:1.13
        build: ./images/nginx/1.13
        ports: 
            - "80:8000"
            - "443:8443"
        environment: 
            - HOSTNAME=l.m2.com
        links:
            - db
            - phpfpm
        volumes: &appvolumes
            - ~/.composer:/var/www/.composer:delegated
            - ./../:/var/www/html
            - sockdata:/sock

    phpfpm:
        image: magento-php:7.3-fpm-2
        build: ./images/php/7.3
        links:
            - db
        volumes: *appvolumes

    db:
        image: percona:5.7
        ports:
            - "3306:3306"
        env_file: env/db.env
        volumes: 
            - dbdata:/var/lib/mysql

    redis:
        image: redis:5.0

    elasticsearch:
        image: magento-elasticsearch:6.5.4-0
        build: ./images/elasticsearch/6.5
        ports:
        - "9200:9200"
        - "9300:9300"

volumes:
    appdata:
    dbdata:
    sockdata: